apiVersion: s3.aws.jet.crossplane.io/v1alpha2
kind: Bucket
metadata:
  name: sample-bucket-agboola
  ns: 
  annotations:
    # This will be the actual bucket name. It must be globally unique, so you
    # probably want to change it before trying to apply this example.
    crossplane.io/external-name: sample-bucket-agboola
spec:
  forProvider:
    region: ca-central-1
    acl: private
    tags:
      Name: sample-bucket-agboola